import { Header } from "@/components/header"
import { Footer } from "@/components/footer"
import Link from "next/link"

export default function AccWing78Page() {
  return (
    <div className="min-h-screen bg-[#f5f5f5]">
      <Header />

      <main className="py-16 lg:py-24">
        <div
          className="max-w-4xl mx-auto"
          style={{
            paddingLeft: "calc(2 / 42 * 100vw)",
            paddingRight: "calc(3 / 42 * 100vw)",
          }}
        >
          {/* Category */}
          <p className="text-[#292929] font-light italic text-sm mb-4">
            Cruising
          </p>

          {/* Title */}
          <h1 className="text-[#292929] font-medium tracking-[0.12em] text-2xl lg:text-3xl mb-2">
            AWA 78 — ACC WING Trimaran
          </h1>

          <p className="text-[#292929] font-light italic text-lg mb-8">
            Tailored, Eco-Conscious Charter for an Adventurous, Sustainable Voyage
          </p>

          {/* Section: Sustainably Powerful */}
          <div className="mb-12">
            <h2 className="text-[#292929] font-medium tracking-[0.12em] text-xl mb-6">
              Sustainably Powerful
            </h2>
            <div className="space-y-4">
              <p className="text-[#292929] font-light italic text-base leading-relaxed text-justify">
                ACCwing is a naturally decarbonized &quot;sailing propulsion&quot; — like an obvious invitation towards zero emissions. Completed with solar panels and electric propulsion, its energy mix is self-sufficient in a still compact format.
              </p>
              <p className="text-[#292929] font-light italic text-base leading-relaxed text-justify">
                Between two moorings, the sport continues with ultra-efficient sailing. The ACC wing delivers lift up to 2.5 times greater than a conventional rig. This tremendous thrust is generated by a patented variable camber activated by internal muscles with very low induced drag. Drag that is also minimized by the bold choice of 3 hulls.
              </p>
              <p className="text-[#292929] font-light italic text-base leading-relaxed text-justify">
                <a 
                  href="https://www.accwingsail.com/en/home/" 
                  target="_blank" 
                  rel="noopener noreferrer"
                  className="underline hover:text-[#555]"
                >
                  Learn more about ACC WING technology
                </a>
              </p>
            </div>
          </div>

          {/* Section: Mast to Design */}
          <div className="mb-12">
            <h2 className="text-[#292929] font-medium tracking-[0.12em] text-xl mb-6">
              Mast to Design
            </h2>
            <div className="space-y-4">
              <p className="text-[#292929] font-light italic text-base leading-relaxed text-justify">
                The lower deck and the tip of the central hull have been designed for a crew of 4 to 6, who will therefore be perfectly available for the guests.
              </p>
              <p className="text-[#292929] font-light italic text-base leading-relaxed text-justify">
                Ultimate luxury: 4 retractable rear platforms allow passengers to enjoy the ocean or the sun via a private 60 m² beach in an absolutely cocooning atmosphere. This huge private beach offers an exceptional setting for all imaginable water sports: diving, surfing, wing foiling.
              </p>
            </div>
          </div>

          {/* Section: Pocket Superyacht */}
          <div className="mb-12">
            <h2 className="text-[#292929] font-medium tracking-[0.12em] text-xl mb-6">
              Pocket Superyacht
            </h2>
            <div className="space-y-4">
              <p className="text-[#292929] font-light italic text-base leading-relaxed text-justify">
                By favoring a design mode centered on ACCwing innovations, they offer a new category of charter sailboat extremely close to a superyacht: the space and privacy are absolutely &quot;unprecedented&quot; on a 78-foot vessel.
              </p>
              <p className="text-[#292929] font-light italic text-base leading-relaxed text-justify">
                With a ratio of 12 clients to 6 crew, the AWA 78 trimaran positions itself as an alternative to motor yachts in terms of comfort, safety, simplicity, and service, with fewer emissions.
              </p>
              <p className="text-[#292929] font-light italic text-base leading-relaxed text-justify">
                The round living cell is incredibly spacious and elegantly distributes towards 6 large cabins, each with its own ensuite bathroom. These rooms, comparable in size to a hotel room, offer ultimate comfort and total privacy for the ship&apos;s passengers.
              </p>
            </div>
          </div>

          {/* Specs */}
          <div className="border-t border-[#e0e0e0] pt-8">
            <h2 className="text-[#292929] font-medium tracking-wider text-sm mb-6">
              Specifications
            </h2>
            <div className="grid grid-cols-2 lg:grid-cols-3 gap-4">
              <div>
                <p className="text-[#292929] font-light italic text-xs mb-1">
                  Length
                </p>
                <p className="text-[#292929] font-medium text-sm">
                  78 ft
                </p>
              </div>
              <div>
                <p className="text-[#292929] font-light italic text-xs mb-1">
                  Type
                </p>
                <p className="text-[#292929] font-medium text-sm">
                  ACC WING Trimaran
                </p>
              </div>
              <div>
                <p className="text-[#292929] font-light italic text-xs mb-1">
                  Guests
                </p>
                <p className="text-[#292929] font-medium text-sm">
                  12
                </p>
              </div>
              <div>
                <p className="text-[#292929] font-light italic text-xs mb-1">
                  Crew
                </p>
                <p className="text-[#292929] font-medium text-sm">
                  4-6
                </p>
              </div>
              <div>
                <p className="text-[#292929] font-light italic text-xs mb-1">
                  Cabins
                </p>
                <p className="text-[#292929] font-medium text-sm">
                  6 with ensuite
                </p>
              </div>
              <div>
                <p className="text-[#292929] font-light italic text-xs mb-1">
                  Beach Platform
                </p>
                <p className="text-[#292929] font-medium text-sm">
                  60 m²
                </p>
              </div>
              <div>
                <p className="text-[#292929] font-light italic text-xs mb-1">
                  Wing Lift
                </p>
                <p className="text-[#292929] font-medium text-sm">
                  2.5x conventional rig
                </p>
              </div>
              <div>
                <p className="text-[#292929] font-light italic text-xs mb-1">
                  Propulsion
                </p>
                <p className="text-[#292929] font-medium text-sm">
                  Solar + Electric
                </p>
              </div>
              <div>
                <p className="text-[#292929] font-light italic text-xs mb-1">
                  Design
                </p>
                <p className="text-[#292929] font-medium text-sm">
                  AWA
                </p>
              </div>
            </div>
          </div>
        </div>
      </main>

      <Footer />
    </div>
  )
}
